SELECT TO_CHAR(A.FECPAGO,'YYYYMM') MES_PAGO,
	   A.MESDEVENGUE PER_DEV,
	   A.TIPAPORTE COD_TIPSALDO,
       SUM(A.MTOACREDITADOSOL * decode(tipmovimiento, 10, 1, 0)) AS ABONOS,
       SUM(A.MTOACREDITADOSOL * decode(tipmovimiento, 10, 0, -1)) AS CARGOS,
       SUM(A.MTOACREDITADOSOL * decode(tipmovimiento, 10, 1, -1)) AS SOLES,
	   decode(A.TIPAPORTE,'I008','COMISIÓN AFP/CMR','I001','PRIMA DE SEGURO','I002','COMISIÓN AFP','I003','COMISION FIJA') DESCRIPCION_SALDO,
	   dta.destipaporte
FROM   UD_ACREDITACIONADM A,
	   md_destipoaporte dta
WHERE  A.FECACREDITACION BETWEEN '15/abr/2017' AND '18/abr/2017'
AND    A.CODCUENTA > '0'
AND    A.CODESTADOACREDITACION = 'I'
AND	   a.tipaporte = dta.tipaporte
GROUP BY 
TO_CHAR(A.FECPAGO,'YYYYMM'), A.MESDEVENGUE,A.TIPAPORTE,dta.destipaporte